### ISSUE TITLE
Number instead Numer in tests?

### ISSUE THREAD

**Issue by demonking** [yiisoft/factory#1]
### What steps will reproduce the problem?
Clone Repository
Run tests
### What is the expected result?
Don't know, if it was planned?
### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      | 
| Operating system |

Shouldn't it be called getNumber? Or is there a reason for calling it getNumer?

./tests/Support/EngineMarkTwo.php:33:    public function getNumer(): int
./tests/Support/EngineMarkOne.php:33:    public function getNumer(): int
./tests/Support/EngineInterface.php:22:    public function getNumer(): int;

**Comment by demonking** [comment]
btw would make a pull request, but don't know, if it was planned, or a mistake :)

**Comment by rugabarbo** [comment]
This is mistake of the getter naming.
Make a PR if you want :)
