### ISSUE TITLE
Regression in container fallback

### ISSUE THREAD

**Issue by samdark** [yiisoft/factory#106]
https://github.com/yiisoft/factory/commit/6d03850b7db5b2bde06e4239948ddb409b988f2c introduced a break in fallback logic. While it is necessary for references not to use fallback as in #102, regular dependencies should still use it.

**Comment by samdark** [comment]
```php
class Main
{
    public function __construct(LoggerInterface $logger)
    {
        // ...
    }
}

$factory->create(Main::class);
```

**Comment by vjik** [comment]
There is no such bug. Regular dependencies use container. Only references don't use fallback to container.
Example with class `Main` correct work now.

**Comment by samdark** [comment]
Verified that it works as expected.
