### ISSUE TITLE
Bug: factory don't use definition indirectly

### ISSUE THREAD

**Issue by vjik** [yiisoft/factory#118]
Test:

```php
public function testCreateByClassIndirectly(): void
{
	$factory = new Factory(
		null,
		[
			EngineInterface::class => EngineMarkOne::class,
			EngineMarkOne::class => [
				'setNumber()' => [42],
			],
		]
	);

	$engine = $factory->create(EngineInterface::class);
	
	$this->assertInstanceOf(EngineMarkOne::class, $engine);
	$this->assertSame(42, $engine->getNumber());
}
```

**Comment by samdark** [comment]
I think current behavior is correct since dependencies are always taken from container, not from a factory definitions.

**Comment by vjik** [comment]
> I think current behavior is correct since dependencies are always taken from container, not from a factory definitions.

`EngineMarkOne` is not dependency, this is object, which will be returned as result of `Factory::create()`.

**Comment by samdark** [comment]
Shouldn't it be the following then?

```php
[
	EngineInterface::class => Reference::to(EngineMarkOne::class),
	EngineMarkOne::class => [
		'setNumber()' => [42],
	],
]
```

**Comment by vjik** [comment]
> Shouldn't it be the following then?
> 
> ```
> 	EngineInterface::class => Reference::to(EngineMarkOne::class),
> ```

Reference always use definition of Factory.
 
I agree with "dependencies are always taken from container, not from a factory definitions.", but in topic test container is null and factory is container for resolve dependencies.
