### ISSUE TITLE
How could I create a new instance by definition

### ISSUE THREAD

**Issue by ChisWill** [yiisoft/factory#140]
Container have definitions like below:
```php
[
    InterfaceX::class => [
        'class' => ClassX::class,
        '__construct()' => [1, 2, 3]
    ]
    // others
];
```
I want to get a new instance of `InterfaceX::class` by `$factory->create(Reference::to(InterfaceX::class))` or other way.
Is there such a function now？

**Comment by vjik** [comment]
`сreate()` there is this function

```php
$factory = new Factory(null, [
    InterfaceX::class => [
        'class' => ClassX::class,
        '__construct()' => [1, 2, 3]
    ]
    // others
]);

$factory->create(InterfaceX::class);
```

**Comment by ChisWill** [comment]
> `сreate()` there is this function
> 
> ```
> $factory = new Factory(null, [
>     InterfaceX::class => [
>         'class' => ClassX::class,
>         '__construct()' => [1, 2, 3]
>     ]
>     // others
> ]);
> 
> $factory->create(InterfaceX::class);
> ```

I know this, but the definitions had been definded and I don't want to repeat it, I want to reference it.

**Comment by vjik** [comment]
`Factory` use for create objects by given definition and `Container` in factory use only for resolve dependencies.

If you need create new instances of `InterfaceX`, then define him in factory, and use factory instead of container.
