### ISSUE TITLE
Ambiguity of references

### ISSUE THREAD

**Issue by vjik** [yiisoft/factory#141]
```php
$container = new Container([
    'color' => Red::class,
]);

$factory = new Factory($container, [
    'color' => Green::class,
    Circle::class => [
        '__construct()' => [Reference::to('color')],
    ],
])
```

What is color of circle? Unclear.

May be need create special for factory new reference `ContainerReference` for create reference to definition in container? This will allow us to determine where to take definition: from factory (`Reference` from `yiisoft/definitions`) or from container (new `ContainerReference` from `yiisoft/factory`).

**Comment by samdark** [comment]
I think in this case it should be green without other options.

**Comment by samdark** [comment]
There are services you get as dependencies defined in container and objects you create defined in factory. In an artificial scenario these may be the of the same interface. In a real scenario, though, the situation you describe is close to be impossible. At least I've tried hard to come up with a case for it and failed.
