### ISSUE TITLE
get() method

### ISSUE THREAD

**Issue by samdark** [yiisoft/factory#18]
Currently `get()` is useless:

1. Its `$params` doesn't do anything.
2. It is useless and is there only because `FactoryInterface` inherits `ContainerInterface`.

How about removing `get()` along with inheritance from `ContainerInteface`?

**Comment by githubjeka** [comment]
I was confused by the very existence of the container in this library, and even more so by the inheritance of the Factory from the Container. These are essentially different things, albeit similar in method names. The purpose of the Factory is to create objects by parameters, and the purpose of the Container is to store entry by IDs and give object on demand.

The user code could use Factory in the ContainerInterface::get(id) method. With the current state of affairs, it is not clear to me where to use your factory, which is also a container.

**Comment by hiqsol** [comment]
Unfortunately it cannot be simply deleted.
It is required for definitions to work.
See https://github.com/yiisoft/factory/blob/master/src/Definitions/DefinitionInterface.php

```php
public function resolve(ContainerInterface $container);
```

Some workaround is necessary.
