### ISSUE TITLE
Fatal Error: DynamicReference incompatible with ReferenceInterface

### ISSUE THREAD

**Issue by vjik** [yiisoft/factory#30]
[ReferenceInterface](https://github.com/yiisoft/factory/blob/606e811dd9576d2e3fafdf6637f184478f2facf1/src/Definitions/ReferenceInterface.php#L7):

```php
public static function to(string $id): Reference;
```

[DynamicReference](https://github.com/yiisoft/factory/blob/606e811dd9576d2e3fafdf6637f184478f2facf1/src/Definitions/DynamicReference.php#L35):

```php
public static function to($definition): DynamicReference
{
    return new self($definition);
}
```

DynamicReference now has fatal error on set `$definition` as array in `DynamicReference::to($definition)`:

`Fatal error: Declaration of Yiisoft\Factory\Definitions\DynamicReference::to($definition): Yiisoft\Factory\Definitions\DynamicReference must be compatible with Yiisoft\Factory\Definitions\ReferenceInterface::to(string $id): Yiisoft\Factory\Definitions\Reference in .\vendor\yiisoft\factory\src\Definitions\DynamicReference.php on line 35`

**Comment by samdark** [comment]
https://github.com/yiisoft/factory/pull/29#discussion_r467088286
