### ISSUE TITLE
Predefined arguments when calling a factory

### ISSUE THREAD

**Issue by roxblnfk** [yiisoft/factory#41]
Since we are now using [Injector to run the callables](https://github.com/yiisoft/factory/blob/539d3e7c6435e86a110223145110dde07c6204fe/src/Definitions/CallableDefinition.php#L23), i suggest adding a predefined argument.
This argument is the same identifier by which the value from the container is requested.

The following example assumes that the parameter name for getting the identifier will be `$id`:
```php
$factory = fn (string $id) => new $id();
$config = [
    'itemA' => $factory,
    'itemB' => $factory,
];
$container->get('itemA');  // Instance of itemA
$container->get('itemB');  // Instance of itemB
```

As you can see from the example, this can help you create common factories for similar objects. A factory can implement any logic internally based on the value of the identifier.

For example:

```php
$factory = function (string $id) {
    $channel = strpos($id, '.') === false ? null : substr($id, strpos($id, '.') + 1);
    
    return new MegaLogger()->withChannel(channel ?? 'main');
};

$dbLogger = $container->get('logger.db');
$mailLogger = $container->get('logger.mail');
```

```php
$factory = function (string $id) use (&$params) {
    $cfg = explode('/', $id)[1] ?? 'default';
    
    return new MegaLogger($params['my-service'][$cfg]);
};

$dbLogger = $container->get('logger.db');
$mailLogger = $container->get('logger.mail');
```

What do you think?

**Comment by samdark** [comment]
Looks a bit too magical to me to use ID of a service to determine service configuration. Also, in majority cases, you won't be able to set any meta information into ID since interface name is used.
