### ISSUE TITLE
Callable collision

### ISSUE THREAD

**Issue by vjik** [yiisoft/factory#52]
### What steps will reproduce the problem?

```php
class MyClass
{
    private string $param;

    public function __construct(string $param)
    {
        $this->param = $param;
    }

    public function getParam(): string
    {
        return $this->param;
    }
}

$factory = new Factory($this->createContainer());
$object = $factory->create(MyClass::class, ['param' => 'date']);
```

### What is the expected result?

Not exception

### What do you get instead?

```
Yiisoft\Injector\MissingRequiredArgumentException
Missing required argument "format" when calling "date".
```

### Additional info

I think need remove support `callable` and use only `\Closure`.

**Comment by hiqsol** [comment]
I've added test for given example in #53. It passes successfully.
Please recheck your example.

**Comment by vjik** [comment]
> I've added test for given example in #53. It passes successfully.
> Please recheck your example.

This is test not equal problem.

Need set value as php function name. I'm added test: https://github.com/yiisoft/factory/pull/53/commits/17e8ce4b188f6f8deac07c4fe02895af57595ce0

**Comment by hiqsol** [comment]
Thank you!
I've added fix.
