### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by viktorprogger** [yiisoft/factory#6]
I had a quick look into `league/container` to see if we can fix tests. Unfortunately, both `yiisoft/di` and `league/container` are not fully compatible with PSR-11 and completely incompatible with each other:
- `yiisoft/di` defines `get($id, array $params)`
- `league/container` defines `get($id, bool $new)`

So I think there is no need to run tests with different implementations of DI container. Or at least we can search for some implementations fully compatible with this standart.

**Comment by samdark** [comment]
Can't we run tests assuming an interface is strictly PSR-11 i.e. do not pass 2nd argument?

**Comment by viktorprogger** [comment]
This depends on the main code, not on tests:
- https://github.com/yiisoft/factory/blob/6614d39101bc2817dbb9de165a65adef3656f9ad/src/Definitions/ClassDefinition.php#L34
- https://github.com/yiisoft/factory/blob/6614d39101bc2817dbb9de165a65adef3656f9ad/src/Definitions/Reference.php#L46
- And PR #5: https://github.com/yiisoft/factory/pull/5/files#diff-8157a0d28a58887c0293ce14b4b0281fR51

**Comment by yiiliveext** [comment]
For what purpose we have the second param in the get()?
I guess that ```$container->get($id, $param)``` is the same as
```php
$container->set($id, [
    'class' => $id,
    '__constract()' => $params
]);
$container->get($id);
``` 
I replaced it in the yiisoft/factory this way and all tests have been passing. Look at https://github.com/yiiliveext/factory/commit/947ccd302a650eb6e0753e0a50c6ff3ea6252ee4

**Comment by samdark** [comment]
@hiqsol do you remember what params were for?

**Comment by yiiliveext** [comment]
> @hiqsol do you remember what params were for?

If it is used in the factory only, I'll merge this commit to PR(https://github.com/yiisoft/factory/pull/8)

**Comment by yiiliveext** [comment]
It is even better, I've removed the PSR-11 incompatibility from the factory too.
https://github.com/yiiliveext/factory/commit/2301b5001392312b77db3e27387dda5c799773fa

**Comment by samdark** [comment]
Factory's parameters argument was meant to be override for what's defined in the config i.e. 

```php
$factory = new Factory($container, [
    UserInterface::class => [
        '__class' => User::class,
        'setName()' => ['Unknown'],
    ],
]);

$andrii = $factory->create(UserInterface::class, [
    'setName()' => ['Andrii'],
]);

$alex = $factory->create(UserInterface::class, [
    'setName()' => ['Alex'],
]);
```

**Comment by yiiliveext** [comment]
Ok, I've created a test, it fails on dev-master. 
```php
public function testClassParametersOverride()
    {
        $container = $this->createContainer();
        $factory = new Factory($container, [
            EngineInterface::class => [
                '__class' => EngineMarkOne::class,
                'setNumber()' => [20],
            ],
        ]);
        $engineOne = $factory->create(EngineInterface::class, [
            'setNumber()' => [30],
        ]);
        $engineTwo = $factory->create(EngineInterface::class, [
            'setNumber()' => [40],
        ]);
        $this->assertEquals(30, $engineOne->getNumber());
        $this->assertEquals(40, $engineTwo->getNumber());
    }
```
Are you wrong?

**Comment by samdark** [comment]
I could be about the syntax. Here it is: https://github.com/yiisoft/factory/blob/6614d39101bc2817dbb9de165a65adef3656f9ad/src/Definitions/ClassDefinition.php#L34

**Comment by yiiliveext** [comment]
And what?  It is absolutly the same as
```php
$container->set($this->class, [
                    'class' => $this->class,
                    '__construct()' => $params
                ]);
                $result = $container->get($this->class);
```
I had a look at the source code of ArrayDefinition and ArrayBuilder, this params are constructor params only.
https://github.com/yiisoft/factory/blob/6614d39101bc2817dbb9de165a65adef3656f9ad/src/Definitions/ArrayDefinition.php#L52
https://github.com/yiisoft/factory/blob/6614d39101bc2817dbb9de165a65adef3656f9ad/src/Definitions/ArrayBuilder.php#L30-L32

**Comment by yiiliveext** [comment]
If you want I can implement functionality as in the test above in my PR. 
This is will be the next syntax.
```php
$engineOne = $factory->create(EngineInterface::class, [
             '__construct' => [SomeClass::class],
             'setNumber()' => [30],
        ]);
```
But I think it It does not make sense, because you can write
```php
$engineOne = $factory->create([
             '__class' => 'EngineInterface::class',
             '__construct' => [SomeClass::class],
             'setNumber()' => [30],
        ]);
```

**Comment by samdark** [comment]
Yeah. You're right.

**Comment by yiiliveext** [comment]
> Yeah. You're right. It does not make sense.

Please note, the second syntax does not work now but I can do.

**Comment by yiiliveext** [comment]
I did some research and concluded that the second param does not make sense. The di/Container implements a singleton pattern, it means the second param will be applied for the first time only, next time it will not be applied because the container will return the previous object. If we want a container with a non-singleton pattern we have to use a factory/Factory.

**Comment by samdark** [comment]
While container implements singleton pattern, factory does not. See https://github.com/yiisoft/factory/blob/master/tests/Unit/AbstractFactoryTest.php#L31

**Comment by yiiliveext** [comment]
> While container implements singleton pattern, factory does not. See https://github.com/yiisoft/factory/blob/master/tests/Unit/AbstractFactoryTest.php#L31

Didn't I write it above?

**Comment by samdark** [comment]
I'm not reading carefully :) Sorry. Need some time to check everything...

**Comment by yiiliveext** [comment]
> I'm not reading carefully :) Sorry. Need some time to check everything...

It would be nice when you look at this branch https://github.com/yiiliveext/factory/tree/factory-fix-alt-exp. There is no second param there and the test above has been passing.

**Comment by viktorprogger** [comment]
It will be easier to see the deffirences in a PR. Please make a PR from your branch.

**Comment by yiiliveext** [comment]
> It will be easier to see the deffirences in a PR. Please make a PR from your branch.

Done. https://github.com/yiisoft/factory/pull/9

**Comment by samdark** [comment]
https://github.com/yiisoft/factory/pull/10

**Comment by samdark** [comment]
Seems this one is fixed.
