### ISSUE TITLE
Re-consider the package

### ISSUE THREAD

**Issue by samdark** [yiisoft/factory#77]
1. Need a list of usages in other packages (except di).
2. Could be replace these usages with something else like injector?

**Comment by yiiliveext** [comment]
> 1. Need a list of usages in other packages (except di).
> 2. Could be replace these usages with something else like injector?

It can't

**Comment by samdark** [comment]
## Widgets use-case

- https://github.com/yiisoft/yii-bulma/blob/master/config/web/field.php
- https://github.com/yiisoft/form/blob/master/src/Widget/Field.php#L27

We have lots of options in the widget https://github.com/yiisoft/form/blob/master/src/Widget/Field.php#L27 with their defaults.

For each concrete CSS-framework (bulma, bootstrap) defaults are adjsuted. Mainly CSS-classes.

For particular `::widget()` call I may want to set my own class.

Therefore, an hierarchy of options is the following:

- Widget options
- Defaults for particular CSS framework (bulma, bootstrap)
- Concrete `widget()` call settings.

**Comment by samdark** [comment]
# Database use-case

https://github.com/yiisoft/db/blob/master/src/Factory/DatabaseFactory.php

**Comment by samdark** [comment]
No more use-cases currently.

**Comment by samdark** [comment]
## Auth client

- https://github.com/yiisoft/yii-auth-client/blob/master/src/OAuth.php#L181
- https://github.com/yiisoft/yii-auth-client/blob/master/src/OAuth.php#L343

**Comment by samdark** [comment]
# Dataview use-case

- https://github.com/yiisoft/yii-dataview/blob/master/src/Factory/GridViewFactory.php#L31

**Comment by samdark** [comment]
# Filesystem use-case

https://github.com/yiisoft/yii-filesystem/blob/master/src/FileStorageServiceProvider.php#L22

**Comment by samdark** [comment]
# Queue-AMQP use-case

https://github.com/yiisoft/yii-queue-amqp/blob/master/src/MessageSerializer.php#L52
