### ISSUE TITLE
Insufficient data for unserializing 

### ISSUE THREAD

**Issue by strorch** [yiisoft/factory#94]
I got a warning in case of usage DynamicReference class.

```
Warning: Insufficient data for unserializing - 6696 required, 6692 present in /app/vendor/opis/closure/functions.php on line 36
```

after dump autoload operation with composer-config-plugin, it serializes files from yiisoft libraries (FileMailer, MessageBodyRenderer, View) and after unserialize I got a lot of warnings.

**Comment by samdark** [comment]
@strorch composer-config-plugin is obsolete and that's its eerror, not factory's. Consider switching to https://github.com/yiisoft/config
